apiVersion: v1
kind: Template
metadata:
  name: generated-cft-template
spec:
  description: Generated CloudFormation Template
  resources:
    - name: generatedCFTResource
      type: Custom::GeneratedCFTResource
      properties:
        ...