AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Healthcare domain in Test environment

Parameters:
  SecurityGroupID:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/HealthCare/resources/SG_id'
  AMIID:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/HealthCare/resources/ami_id'
  PublicSubnetID:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/HealthCare/resources/psubnet_id'
  PrivateSubnetID:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/HealthCare/resources/privatesubnet_id'

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.large'
      SecurityGroupIds:
        - !Ref SecurityGroupID
      ImageId: !Ref AMIID
      SubnetId: !Ref PublicSubnetID
      Tags:
        - Key: Name
          Value: 'webapp'
        - Key: Application
          Value: 'nginx'
        - Key: Domain
          Value: 'Healthcare'
        - Key: Environment
          Value: 'Test'

Outputs:
  InstanceId:
    Description: 'Instance ID of the newly created EC2 instance'
    Value: !Ref EC2Instance